baseURL = ""
relativeurls = true
languageCode = "en-US"
#defaultContentLanguage = "en"
metaDataFormat = "yaml"
title = "BridgeScorer"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir= true
uglyurls = true

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  description = "Documentation for Bridge Score Keeper"
  showVisitedLinks = true
  # to set the version, set the environment variable HUGO_BRIDGESCORERVERSION to the version
  bridgeScorerVersion = "unknown version"
  
# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Help"
weight = 1
languageName = "English"

[[menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/thebridsk/bridgescorer"
weight = 10

[[menu.shortcuts]] 
name = "Play"
identifier = "play"
url = "/play.html"
weight = 20