baseURL = ""
relativeurls = true
languageCode = "en-US"
#defaultContentLanguage = "en"
metaDataFormat = "yaml"
title = "BridgeScorer"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir= true
uglyurls = true
bridgeScorerVersion = "unknown version from site"

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  description = "Documentation for Bridge Score Keeper"
  showVisitedLinks = true
  # to set the version, set the environment variable HUGO_BRIDGESCORERVERSION to the version
  bridgeScorerVersion = "unknown version"
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/thebridsk/bridgescorerdocs/tree/master/docs/content/"
  # 
  disableInlineCopyToClipBoard = true
  
# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "BridgeScorer Help"
weight = 1
languageName = "English"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/thebridsk/bridgescorer"
weight = 10
